#!/usr/bin/env bash
# transfers a file from our client to a server
path_of_file = "$1"
Ip = "$2"
username = "$3"
path_of_ssh = "$4"

if [ $# -lt 4 ]
then
	echo 'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY'
else
	scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~
fi
