#!/usr/bin/env bash
# configuring the server to some specifications given
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
server nginx restart
