#!/usr/bin/env bash
#displays the content of the file /etc/passwd
#display only username, user id, Home directory path for the user
file="/etc/passwd"
while IFS= read -r line
do
	echo "$line" | cut -d':' ---fields=1,3,6
done < "$file"
