#!/usr/bin/env bash
#displays the content of the file /etc/passwd, using the while loop + IFS
filename="/etc/passwd"
while IFS=: read -r username password userid groupname comment homedir shell;
do
	echo "The user $username is part of the $groupname gang,"
	echo "lives in $homedir and rides $shell."
	echo "$userid's place is protected by the passcode $password,"
	echo "more info about the user here: comment"
done < $filename
