#!/usr/bin/env bash
# This script is displaying "Best School" 10 times and write hi on the 9th line
a="1"
while [ $a == 10 ];
do
	if [ $a -eq 9 ]
	then
		echo "Hi"
	else
		echo "Best School"
	fi
	(( a++ ))
done
