#!/usr/bin/env bash
# This script is displaying "Best School" 10 times and write hi on the 9th line
a="0"
while [ $a -lt 11 ];
do
	if [ $a = 9 ]
	then
		echo "Hi"
	else
		echo "Best School"
	fi
	((a+=1))
done
